/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux paldier-VirtualBox 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "Thu Dec 12 20:50:18 CST 2019"
#define BUILD_ENV_SRCDIR "/home/paldier/68u/release/src/router/samba-3.6.x_opwrt/source/source3"
#define BUILD_ENV_BUILDDIR "/home/paldier/68u/release/src/router/samba-3.6.x_opwrt/source/source3"
#define BUILD_ENV_USER "paldier"
#define BUILD_ENV_HOST "paldier-VirtualBox"
#define BUILD_ENV_COMPILER "arm-brcm-linux-uclibcgnueabi-gcc"
#endif /* _BUILD_ENV_H */
