/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

#include "version.h"
const char *version_string = "1.20.1";
const char *compilation_string = (char *)0; // "arm-brcm-linux-uclibcgnueabi-gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/etc/wgetrc\" -DLOCALEDIR=\"/usr/share/locale\" -I. -I../lib -I../lib -I/home/paldier/68u/release/src-rt-6.x.4708/router/arm-uclibc/stage/usr/include -DHAVE_LIBSSL -DNDEBUG -Os -Wall -DLINUX26 -DCONFIG_BCMWL5 -DDEBUG_NOISY -DDEBUG_RCTEST -pipe -DBCMWPA2 -DBCMARM -fno-strict-aliasing -marm -DRTCONFIG_NVRAM_64K -DLINUX_KERNEL_VERSION=132644 -ffunction-sections -fdata-sections -I/home/paldier/68u/release/src-rt-6.x.4708/router/arm-uclibc/stage/usr/include";
const char *link_string = (char *)0; // "arm-brcm-linux-uclibcgnueabi-gcc -std=gnu99 -DHAVE_LIBSSL -DNDEBUG -Os -Wall -DLINUX26 -DCONFIG_BCMWL5 -DDEBUG_NOISY -DDEBUG_RCTEST -pipe -DBCMWPA2 -DBCMARM -fno-strict-aliasing -marm -DRTCONFIG_NVRAM_64K -DLINUX_KERNEL_VERSION=132644 -ffunction-sections -fdata-sections -I/home/paldier/68u/release/src-rt-6.x.4708/router/arm-uclibc/stage/usr/include -lgcc_s -Wl,--gc-sections -L/home/paldier/68u/release/src-rt-6.x.4708/router/arm-uclibc/stage/usr/lib -pthread -lssl -lcrypto -lz openssl.o ../lib/libgnu.a -lcrypto /home/paldier/68u/release/src-rt-6.x.4708/router/arm-uclibc/stage/usr/lib/libiconv.so ";
