#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','a','r','m','-','b','r','c','m',
        '-','l','i','n','u','x','-','u','c','l','i','b','c','g','n','u','e','a',
        'b','i','-','g','c','c',' ','-','f','P','I','C',' ','-','D','O','P','E',
        'N','S','S','L','_','P','I','C',' ','-','D','O','P','E','N','S','S','L',
        '_','T','H','R','E','A','D','S',' ','-','D','_','R','E','E','N','T','R',
        'A','N','T',' ','-','D','D','S','O','_','D','L','F','C','N',' ','-','D',
        'H','A','V','E','_','D','L','F','C','N','_','H',' ','-','O','3',' ','-',
        'W','a','l','l',' ','-','f','o','m','i','t','-','f','r','a','m','e','-',
        'p','o','i','n','t','e','r',' ','-','O','2',' ','-','f','f','u','n','c',
        't','i','o','n','-','s','e','c','t','i','o','n','s',' ','-','f','d','a',
        't','a','-','s','e','c','t','i','o','n','s',' ','-','W','a',',','-','-',
        'n','o','e','x','e','c','s','t','a','c','k',' ','-','D','O','P','E','N',
        'S','S','L','_','N','O','_','E','R','R',' ','-','D','O','P','E','N','S',
        'S','L','_','B','N','_','A','S','M','_','M','O','N','T',' ','-','D','O',
        'P','E','N','S','S','L','_','B','N','_','A','S','M','_','G','F','2','m',
        ' ','-','D','S','H','A','1','_','A','S','M',' ','-','D','S','H','A','2',
        '5','6','_','A','S','M',' ','-','D','S','H','A','5','1','2','_','A','S',
        'M',' ','-','D','A','E','S','_','A','S','M',' ','-','D','B','S','A','E',
        'S','_','A','S','M',' ','-','D','G','H','A','S','H','_','A','S','M','\0'
    };
    #define PLATFORM "platform: linux-armv4"
    #define DATE "built on: Wed Dec 11 13:34:30 2019"
#endif
